const topicBank = [


	// ==========================================================================================	
	// FRIENDSHIP & SOCIAL LIFE
	// ==========================================================================================
	{ text: "A friendship that had a big impact on me", categories: ["Friendship & Social Life"] },
	{ text: "A time I met someone I’ll never forget", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt like I truly belonged", categories: ["Friendship & Social Life"] },
	{ text: "A time I completely misunderstood someone", categories: ["Friendship & Social Life"] },
	{ text: "A moment that strengthened a friendship", categories: ["Friendship & Social Life"] },
	{ text: "A time I made a new connection unexpectedly", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized the value of friendship", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to navigate a social situation", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt out of place socially", categories: ["Friendship & Social Life"] },
	{ text: "A time I had a great conversation with someone", categories: ["Friendship & Social Life"] },

	{ text: "A moment that made me laugh with friends", categories: ["Friendship & Social Life"] },
	{ text: "A time everything became awkward very quickly", categories: ["Friendship & Social Life"] },
	{ text: "A moment I said the wrong thing at the wrong time", categories: ["Friendship & Social Life"] },
	{ text: "A time I tried to make a good impression", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt completely understood", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to step outside my social comfort zone", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized someone was important to me", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to reconnect with someone", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt a strong sense of connection", categories: ["Friendship & Social Life"] },
	{ text: "A time I misread a social situation", categories: ["Friendship & Social Life"] },

	{ text: "A moment I felt included", categories: ["Friendship & Social Life"] },
	{ text: "A time I felt left out", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized how different people can be", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to adapt to a group dynamic", categories: ["Friendship & Social Life"] },
	{ text: "A moment I learned something from a friend", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to support someone else", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt appreciated by others", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to be honest with a friend", categories: ["Friendship & Social Life"] },
	{ text: "A moment that changed a relationship", categories: ["Friendship & Social Life"] },
	{ text: "A time I saw someone in a new light", categories: ["Friendship & Social Life"] },

	{ text: "A moment I realized the importance of communication", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to navigate a misunderstanding", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt closer to someone", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to step up in a social situation", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt unsure how to act", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to adjust to a new social environment", categories: ["Friendship & Social Life"] },
	{ text: "A moment I learned something about people", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to read the room", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt comfortable being myself", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to break the ice", categories: ["Friendship & Social Life"] },

	{ text: "A moment I realized how important connection is", categories: ["Friendship & Social Life"] },
	{ text: "A time I made a lasting impression on someone", categories: ["Friendship & Social Life"] },
	{ text: "A moment I saw the impact of small interactions", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to be patient with someone", categories: ["Friendship & Social Life"] },
	{ text: "A moment I learned the value of listening", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to deal with an awkward silence", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized how much people influence each other", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to navigate different personalities", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt energized by being around others", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to set a boundary with someone", categories: ["Friendship & Social Life"] },

	{ text: "A moment I realized friendships evolve over time", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to let a friendship change naturally", categories: ["Friendship & Social Life"] },
	{ text: "A moment I saw the value of being present with others", categories: ["Friendship & Social Life"] },
	{ text: "A time I had to trust someone else", categories: ["Friendship & Social Life"] },
	{ text: "A moment I felt supported by others", categories: ["Friendship & Social Life"] },
	{ text: "A time I learned something about myself through others", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized how connection shapes experience", categories: ["Friendship & Social Life"] },
	{ text: "A time I chose to reach out instead of withdraw", categories: ["Friendship & Social Life"] },
	{ text: "A moment I realized how small interactions matter", categories: ["Friendship & Social Life"] },
	{ text: "What friendship means to me", categories: ["Friendship & Social Life"] },	

	// ==========================================================================================	
	// GROWING UP
	// ==========================================================================================	
	{ text: "A childhood memory that still makes me smile", categories: ["Growing Up"] },
	{ text: "The first time I felt truly independent", categories: ["Growing Up"] },
	{ text: "A lesson I didn’t appreciate until later", categories: ["Growing Up"] },
	{ text: "What I thought adulthood would be like", categories: ["Growing Up"] },
	{ text: "A moment I realized I was growing up", categories: ["Growing Up"] },
	{ text: "The influence of someone who raised me", categories: ["Growing Up"] },
	{ text: "A rule I didn’t understand as a kid", categories: ["Growing Up"] },
	{ text: "Something I used to believe as a child", categories: ["Growing Up"] },
	{ text: "A childhood habit I’ve never outgrown", categories: ["Growing Up"] },
	{ text: "The first responsibility that felt real", categories: ["Growing Up"] },

	{ text: "A moment I wanted to grow up faster", categories: ["Growing Up"] },
	{ text: "A time I realized things were changing", categories: ["Growing Up"] },
	{ text: "What I’ve learned about growing older", categories: ["Growing Up"] },
	{ text: "A childhood fear I eventually overcame", categories: ["Growing Up"] },
	{ text: "A memory that shaped who I am today", categories: ["Growing Up"] },
	{ text: "The difference between then and now", categories: ["Growing Up"] },
	{ text: "A time I learned responsibility the hard way", categories: ["Growing Up"] },
	{ text: "A tradition from my childhood", categories: ["Growing Up"] },
	{ text: "A moment I saw the world differently", categories: ["Growing Up"] },
	{ text: "What I would tell my younger self", categories: ["Growing Up"] },

	{ text: "A time I felt misunderstood growing up", categories: ["Growing Up"] },
	{ text: "A moment I felt proud as a kid", categories: ["Growing Up"] },
	{ text: "The role of imagination in my childhood", categories: ["Growing Up"] },
	{ text: "A time I learned from a mistake early in life", categories: ["Growing Up"] },
	{ text: "The first time I questioned something I was taught", categories: ["Growing Up"] },
	{ text: "A moment that changed how I saw my family", categories: ["Growing Up"] },
	{ text: "What growing up taught me about people", categories: ["Growing Up"] },
	{ text: "A time I had to grow up quickly", categories: ["Growing Up"] },
	{ text: "The first time I felt truly responsible for something", categories: ["Growing Up"] },
	{ text: "A memory that feels different now than it did then", categories: ["Growing Up"] },

	{ text: "What I thought was important as a child", categories: ["Growing Up"] },
	{ text: "A time I wanted to be someone else", categories: ["Growing Up"] },
	{ text: "A lesson that stayed with me over time", categories: ["Growing Up"] },
	{ text: "The first time I realized adults don’t know everything", categories: ["Growing Up"] },
	{ text: "A moment I felt caught between two stages of life", categories: ["Growing Up"] },
	{ text: "Something I had to learn on my own", categories: ["Growing Up"] },
	{ text: "The impact of a childhood friendship", categories: ["Growing Up"] },
	{ text: "A time I discovered my own voice", categories: ["Growing Up"] },
	{ text: "A moment I understood consequences", categories: ["Growing Up"] },
	{ text: "What growing up has taught me about change", categories: ["Growing Up"] },

	{ text: "A time I had to let go of something from my childhood", categories: ["Growing Up"] },
	{ text: "The first time I felt like an adult", categories: ["Growing Up"] },
	{ text: "A moment I realized I had changed", categories: ["Growing Up"] },
	{ text: "Something I see differently now than I used to", categories: ["Growing Up"] },
	{ text: "A time I had to take ownership of my actions", categories: ["Growing Up"] },
	{ text: "A memory that still influences me today", categories: ["Growing Up"] },
	{ text: "The balance between holding on and moving forward", categories: ["Growing Up"] },
	{ text: "A time I learned patience as a child", categories: ["Growing Up"] },
	{ text: "What I’ve gained from growing up", categories: ["Growing Up"] },
	{ text: "A moment that helped define who I am", categories: ["Growing Up"] },

	{ text: "A time I realized I was no longer a kid", categories: ["Growing Up"] },
	{ text: "The first time I made a decision for myself", categories: ["Growing Up"] },
	{ text: "A lesson I carry with me into adulthood", categories: ["Growing Up"] },
	{ text: "What growing up has taught me about myself", categories: ["Growing Up"] },
	{ text: "A moment I saw things more clearly with age", categories: ["Growing Up"] },
	{ text: "The role of experience in shaping who I am", categories: ["Growing Up"] },
	{ text: "A time I learned the value of responsibility", categories: ["Growing Up"] },
	{ text: "What I’ve outgrown—and what I haven’t", categories: ["Growing Up"] },
	{ text: "A moment I embraced who I was becoming", categories: ["Growing Up"] },
	{ text: "What growing up really means to me", categories: ["Growing Up"] },


	// ==========================================================================================		
	// HOLIDAY & VACATION
	// ==========================================================================================
	{ text: "A vacation that didn’t go as planned", categories: ["Holiday & Vacation"] },
	{ text: "My most memorable holiday experience", categories: ["Holiday & Vacation"] },
	{ text: "A trip I will never forget", categories: ["Holiday & Vacation"] },
	{ text: "The best food I’ve ever had while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A moment that defined a vacation for me", categories: ["Holiday & Vacation"] },
	{ text: "A time I got lost while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A holiday tradition I look forward to", categories: ["Holiday & Vacation"] },
	{ text: "The difference between expectation and reality on a trip", categories: ["Holiday & Vacation"] },
	{ text: "A place that surprised me", categories: ["Holiday & Vacation"] },
	{ text: "My favorite way to spend a holiday", categories: ["Holiday & Vacation"] },

	{ text: "A trip that taught me something unexpected", categories: ["Holiday & Vacation"] },
	{ text: "A time everything went wrong on vacation", categories: ["Holiday & Vacation"] },
	{ text: "The most relaxing moment I’ve ever had", categories: ["Holiday & Vacation"] },
	{ text: "A holiday memory from childhood", categories: ["Holiday & Vacation"] },
	{ text: "A place I would visit again in a heartbeat", categories: ["Holiday & Vacation"] },
	{ text: "A travel experience that changed my perspective", categories: ["Holiday & Vacation"] },
	{ text: "The most spontaneous trip I’ve taken", categories: ["Holiday & Vacation"] },
	{ text: "A moment I felt completely present on vacation", categories: ["Holiday & Vacation"] },
	{ text: "A time I stepped outside my comfort zone while traveling", categories: ["Holiday & Vacation"] },
	{ text: "The most beautiful place I’ve ever seen", categories: ["Holiday & Vacation"] },

	{ text: "A travel mistake I’ll never make again", categories: ["Holiday & Vacation"] },
	{ text: "A time I packed completely wrong", categories: ["Holiday & Vacation"] },
	{ text: "The most unexpected part of a trip", categories: ["Holiday & Vacation"] },
	{ text: "A moment I truly disconnected from everything", categories: ["Holiday & Vacation"] },
	{ text: "A holiday that didn’t feel like a holiday", categories: ["Holiday & Vacation"] },
	{ text: "A trip that was better than I expected", categories: ["Holiday & Vacation"] },
	{ text: "A time I had to adapt quickly while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A place that felt like home even though it wasn’t", categories: ["Holiday & Vacation"] },
	{ text: "A travel story I always tell", categories: ["Holiday & Vacation"] },
	{ text: "A moment I laughed uncontrollably on a trip", categories: ["Holiday & Vacation"] },

	{ text: "The longest journey I’ve taken", categories: ["Holiday & Vacation"] },
	{ text: "A time I learned something new about myself while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A holiday that meant more than I expected", categories: ["Holiday & Vacation"] },
	{ text: "A trip where everything just worked out", categories: ["Holiday & Vacation"] },
	{ text: "A moment I realized the value of the experience over the destination", categories: ["Holiday & Vacation"] },
	{ text: "A time I connected with someone while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A place I didn’t want to leave", categories: ["Holiday & Vacation"] },
	{ text: "A moment that made a trip unforgettable", categories: ["Holiday & Vacation"] },
	{ text: "A time I saw something completely new", categories: ["Holiday & Vacation"] },
	{ text: "A holiday that didn’t go as expected—but worked out anyway", categories: ["Holiday & Vacation"] },

	{ text: "A time I underestimated a trip", categories: ["Holiday & Vacation"] },
	{ text: "A moment that made me appreciate where I was", categories: ["Holiday & Vacation"] },
	{ text: "A trip that taught me patience", categories: ["Holiday & Vacation"] },
	{ text: "A place that changed how I see the world", categories: ["Holiday & Vacation"] },
	{ text: "A time I had to slow down and just enjoy the moment", categories: ["Holiday & Vacation"] },
	{ text: "A travel experience that didn’t match the photos", categories: ["Holiday & Vacation"] },
	{ text: "A moment I felt completely free", categories: ["Holiday & Vacation"] },
	{ text: "A holiday that brought people together", categories: ["Holiday & Vacation"] },
	{ text: "A trip that felt too short", categories: ["Holiday & Vacation"] },
	{ text: "A time I tried something new while traveling", categories: ["Holiday & Vacation"] },

	{ text: "A moment I realized how big the world is", categories: ["Holiday & Vacation"] },
	{ text: "A trip I would plan differently next time", categories: ["Holiday & Vacation"] },
	{ text: "A place that exceeded all expectations", categories: ["Holiday & Vacation"] },
	{ text: "A time I made the most of a small moment on vacation", categories: ["Holiday & Vacation"] },
	{ text: "A travel experience that made me laugh later", categories: ["Holiday & Vacation"] },
	{ text: "A moment I felt out of my element while traveling", categories: ["Holiday & Vacation"] },
	{ text: "A holiday that reminded me what matters", categories: ["Holiday & Vacation"] },
	{ text: "A trip that changed my routine or habits", categories: ["Holiday & Vacation"] },
	{ text: "A moment I realized the journey mattered more than the plan", categories: ["Holiday & Vacation"] },
	{ text: "What a perfect vacation looks like to me", categories: ["Holiday & Vacation"] },	
	
	
	// ==========================================================================================	
  // HUMOROUS
	// ==========================================================================================
  { text: "The most embarrassing thing that ever happened to me", categories: ["Humorous"] },
  { text: "If I ruled the world for a day", categories: ["Humorous"] },
  { text: "My worst habit explained", categories: ["Humorous"] },
  { text: "Why I would survive a zombie apocalypse", categories: ["Humorous"] },
  { text: "The dangers of procrastination", categories: ["Humorous"] },
  { text: "A day where everything went wrong", categories: ["Humorous"] },
  { text: "Why mornings are overrated", categories: ["Humorous"] },
  { text: "My inner monologue revealed", categories: ["Humorous"] },
  { text: "If animals could talk", categories: ["Humorous"] },
  { text: "The chaos of everyday life", categories: ["Humorous"] },
	
	{ text: "Why I would never survive in the wild", categories: ["Humorous"] },
	{ text: "The most unnecessary thing I’ve ever stressed about", categories: ["Humorous"] },
	{ text: "If my life had a laugh track", categories: ["Humorous"] },
	{ text: "The one thing I always do at the worst possible time", categories: ["Humorous"] },
	{ text: "Why I should come with a warning label", categories: ["Humorous"] },
	{ text: "The art of overthinking everything", categories: ["Humorous"] },
	{ text: "A completely normal situation that I made awkward", categories: ["Humorous"] },
	{ text: "Why I can’t trust myself in certain situations", categories: ["Humorous"] },
	{ text: "If my brain had a customer service line", categories: ["Humorous"] },
	{ text: "The things I thought would be easy as an adult", categories: ["Humorous"] },

	{ text: "A skill I thought I had until I really needed it", categories: ["Humorous"] },
	{ text: "Why I always learn things the hard way", categories: ["Humorous"] },
	{ text: "If my habits were a personality", categories: ["Humorous"] },
	{ text: "The most dramatic moment of my life that didn’t matter", categories: ["Humorous"] },
	{ text: "Why simple tasks become complicated for me", categories: ["Humorous"] },
	{ text: "The time I was confidently wrong", categories: ["Humorous"] },
	{ text: "If my life were narrated honestly", categories: ["Humorous"] },
	{ text: "The unexpected consequences of a small decision", categories: ["Humorous"] },
	{ text: "Why I should not be left unsupervised", categories: ["Humorous"] },
	{ text: "A moment where everything escalated too quickly", categories: ["Humorous"] },

	{ text: "The difference between my plans and reality", categories: ["Humorous"] },
	{ text: "Why I always think it will take five minutes", categories: ["Humorous"] },
	{ text: "If I could go back and warn myself about one thing", categories: ["Humorous"] },
	{ text: "The most ridiculous thing I’ve convinced myself of", categories: ["Humorous"] },
	{ text: "Why I always pick the wrong moment", categories: ["Humorous"] },
	{ text: "A time I tried to impress someone and failed", categories: ["Humorous"] },
	{ text: "If my inner voice had no filter", categories: ["Humorous"] },
	{ text: "The one situation where I completely lose logic", categories: ["Humorous"] },
	{ text: "Why I never learn my lesson the first time", categories: ["Humorous"] },
	{ text: "The most unnecessary panic I’ve ever had", categories: ["Humorous"] },

	{ text: "If my daily routine were a comedy sketch", categories: ["Humorous"] },
	{ text: "The things I say in my head versus out loud", categories: ["Humorous"] },
	{ text: "Why I always regret my decisions later", categories: ["Humorous"] },
	{ text: "A time I took something way too seriously", categories: ["Humorous"] },
	{ text: "If I had to explain myself to myself", categories: ["Humorous"] },
	{ text: "The most awkward version of myself", categories: ["Humorous"] },
	{ text: "Why I should not trust my first instinct", categories: ["Humorous"] },
	{ text: "The moment I knew I messed up", categories: ["Humorous"] },
	{ text: "If my life had subtitles", categories: ["Humorous"] },
	{ text: "The most chaotic version of a normal day", categories: ["Humorous"] },

	{ text: "Why I always think I can get away with it", categories: ["Humorous"] },
	{ text: "A time I made things worse instead of better", categories: ["Humorous"] },
	{ text: "If I had a personal theme song at the wrong moments", categories: ["Humorous"] },
	{ text: "The most unnecessary risk I’ve taken", categories: ["Humorous"] },
	{ text: "Why I never stick to my original plan", categories: ["Humorous"] },
	{ text: "A moment I wish I could rewind instantly", categories: ["Humorous"] },
	{ text: "If my excuses were actually honest", categories: ["Humorous"] },
	{ text: "The one thing I always underestimate", categories: ["Humorous"] },
	{ text: "Why I always think ‘this will be fine’", categories: ["Humorous"] },
	{ text: "A situation where I had no good options", categories: ["Humorous"] },	

	// ==========================================================================================	
  // INSPIRATIONAL
	// ==========================================================================================		
  { text: "You are stronger than you think", categories: ["Inspirational"] },
  { text: "Failure is the path to success", categories: ["Inspirational"] },
  { text: "Small habits create big change", categories: ["Inspirational"] },
  { text: "Courage starts with discomfort", categories: ["Inspirational"] },
  { text: "Consistency beats intensity", categories: ["Inspirational"] },
  { text: "Your mindset shapes your reality", categories: ["Inspirational"] },
  { text: "Growth begins where comfort ends", categories: ["Inspirational"] },
  { text: "Believe before you achieve", categories: ["Inspirational"] },
  { text: "Resilience is built, not given", categories: ["Inspirational"] },
  { text: "Progress over perfection", categories: ["Inspirational"] },
	
	{ text: "Your story is still being written", categories: ["Inspirational"] },
	{ text: "Strength is revealed in adversity", categories: ["Inspirational"] },
	{ text: "You are closer than you think", categories: ["Inspirational"] },
	{ text: "The power of showing up", categories: ["Inspirational"] },
	{ text: "Every step counts", categories: ["Inspirational"] },
	{ text: "Change begins within", categories: ["Inspirational"] },
	{ text: "The courage to continue", categories: ["Inspirational"] },
	{ text: "Your voice matters", categories: ["Inspirational"] },
	{ text: "Small wins build greatness", categories: ["Inspirational"] },
	{ text: "The strength to begin again", categories: ["Inspirational"] },

	{ text: "You have more control than you think", categories: ["Inspirational"] },
	{ text: "Growth is a choice", categories: ["Inspirational"] },
	{ text: "The beauty of persistence", categories: ["Inspirational"] },
	{ text: "You are capable of more", categories: ["Inspirational"] },
	{ text: "Momentum starts with one step", categories: ["Inspirational"] },
	{ text: "The power of belief", categories: ["Inspirational"] },
	{ text: "Your limits are not fixed", categories: ["Inspirational"] },
	{ text: "Progress is still progress", categories: ["Inspirational"] },
	{ text: "The strength of starting small", categories: ["Inspirational"] },
	{ text: "You are not behind", categories: ["Inspirational"] },

	{ text: "Confidence is built through action", categories: ["Inspirational"] },
	{ text: "The courage to be seen", categories: ["Inspirational"] },
	{ text: "What you focus on grows", categories: ["Inspirational"] },
	{ text: "The power of consistency over time", categories: ["Inspirational"] },
	{ text: "You are allowed to evolve", categories: ["Inspirational"] },
	{ text: "The strength in vulnerability", categories: ["Inspirational"] },
	{ text: "Every day is a new opportunity", categories: ["Inspirational"] },
	{ text: "Your effort matters", categories: ["Inspirational"] },
	{ text: "The discipline of self-belief", categories: ["Inspirational"] },
	{ text: "You can rewrite your narrative", categories: ["Inspirational"] },

	{ text: "The value of patience", categories: ["Inspirational"] },
	{ text: "You are stronger than your doubts", categories: ["Inspirational"] },
	{ text: "The importance of taking the first step", categories: ["Inspirational"] },
	{ text: "You are not your past", categories: ["Inspirational"] },
	{ text: "The gift of resilience", categories: ["Inspirational"] },
	{ text: "Your journey is unique", categories: ["Inspirational"] },
	{ text: "The power of staying the course", categories: ["Inspirational"] },
	{ text: "You are enough as you are", categories: ["Inspirational"] },
	{ text: "The strength to keep going", categories: ["Inspirational"] },
	{ text: "Success is built daily", categories: ["Inspirational"] },

	{ text: "The courage to try again", categories: ["Inspirational"] },
	{ text: "You are capable of change", categories: ["Inspirational"] },
	{ text: "The impact of a single decision", categories: ["Inspirational"] },
	{ text: "You have what it takes", categories: ["Inspirational"] },
	{ text: "The strength to choose differently", categories: ["Inspirational"] },
	{ text: "Your potential is limitless", categories: ["Inspirational"] },
	{ text: "The power of a positive mindset", categories: ["Inspirational"] },
	{ text: "You are building something meaningful", categories: ["Inspirational"] },
	{ text: "The importance of believing in yourself", categories: ["Inspirational"] },
	{ text: "Every challenge carries an opportunity", categories: ["Inspirational"] },

	// ==========================================================================================	
  // LIFE EXPERIENCE
	// ==========================================================================================		
  { text: "A moment that changed my life", categories: ["Life Experience"] },
  { text: "A lesson I learned the hard way", categories: ["Life Experience"] },
  { text: "A time I failed and recovered", categories: ["Life Experience"] },
  { text: "My most meaningful relationship", categories: ["Life Experience"] },
  { text: "A challenge that shaped me", categories: ["Life Experience"] },
  { text: "A decision I will never regret", categories: ["Life Experience"] },
  { text: "A time I stepped outside my comfort zone", categories: ["Life Experience"] },
  { text: "A moment of unexpected growth", categories: ["Life Experience"] },
  { text: "Something I once feared", categories: ["Life Experience"] },
  { text: "A turning point in my journey", categories: ["Life Experience"] },
	
	{ text: "A time I surprised myself", categories: ["Life Experience"] },
	{ text: "A moment I had to trust my instincts", categories: ["Life Experience"] },
	{ text: "A time I took a leap of faith", categories: ["Life Experience"] },
	{ text: "A situation that tested my patience", categories: ["Life Experience"] },
	{ text: "A time I had to let go", categories: ["Life Experience"] },
	{ text: "A lesson I learned from someone else", categories: ["Life Experience"] },
	{ text: "A moment I felt truly proud of myself", categories: ["Life Experience"] },
	{ text: "A time I had to make a difficult choice", categories: ["Life Experience"] },
	{ text: "A moment I realized something important", categories: ["Life Experience"] },
	{ text: "A time I followed my curiosity", categories: ["Life Experience"] },

	{ text: "A time I stood up for myself", categories: ["Life Experience"] },
	{ text: "A time I stood up for someone else", categories: ["Life Experience"] },
	{ text: "A moment I felt completely out of place", categories: ["Life Experience"] },
	{ text: "A time I had to adapt quickly", categories: ["Life Experience"] },
	{ text: "A time I made an unexpected connection", categories: ["Life Experience"] },
	{ text: "A moment I changed my perspective", categories: ["Life Experience"] },
	{ text: "A time I overcame self-doubt", categories: ["Life Experience"] },
	{ text: "A situation that didn’t go as planned", categories: ["Life Experience"] },
	{ text: "A time I had to start over", categories: ["Life Experience"] },
	{ text: "A moment I felt truly present", categories: ["Life Experience"] },

	{ text: "A time I learned something the hard way again", categories: ["Life Experience"] },
	{ text: "A time I realized I was wrong", categories: ["Life Experience"] },
	{ text: "A moment that taught me humility", categories: ["Life Experience"] },
	{ text: "A time I had to ask for help", categories: ["Life Experience"] },
	{ text: "A moment I felt deeply grateful", categories: ["Life Experience"] },
	{ text: "A time I made a bold decision", categories: ["Life Experience"] },
	{ text: "A moment that felt like a fresh start", categories: ["Life Experience"] },
	{ text: "A time I discovered something new about myself", categories: ["Life Experience"] },
	{ text: "A time I had to be patient for results", categories: ["Life Experience"] },
	{ text: "A moment that felt bigger than me", categories: ["Life Experience"] },

	{ text: "A time I followed through on a commitment", categories: ["Life Experience"] },
	{ text: "A moment I felt misunderstood", categories: ["Life Experience"] },
	{ text: "A time I had to adjust my expectations", categories: ["Life Experience"] },
	{ text: "A time I embraced change", categories: ["Life Experience"] },
	{ text: "A moment I felt a sense of belonging", categories: ["Life Experience"] },
	{ text: "A time I had to slow down", categories: ["Life Experience"] },
	{ text: "A time I made the most of a small opportunity", categories: ["Life Experience"] },
	{ text: "A moment I saw things clearly", categories: ["Life Experience"] },
	{ text: "A time I trusted the process", categories: ["Life Experience"] },
	{ text: "A moment I realized how far I’ve come", categories: ["Life Experience"] },

	{ text: "A time I took responsibility for something", categories: ["Life Experience"] },
	{ text: "A moment I felt inspired by someone", categories: ["Life Experience"] },
	{ text: "A time I had to rethink my approach", categories: ["Life Experience"] },
	{ text: "A moment I felt completely in the flow", categories: ["Life Experience"] },
	{ text: "A time I made peace with something", categories: ["Life Experience"] },
	{ text: "A moment that reminded me what matters", categories: ["Life Experience"] },
	{ text: "A time I chose growth over comfort", categories: ["Life Experience"] },
	{ text: "A moment I trusted myself fully", categories: ["Life Experience"] },
	{ text: "A time I found clarity after confusion", categories: ["Life Experience"] },
	{ text: "A moment I realized the value of persistence", categories: ["Life Experience"] },
	
	// ==========================================================================================
	// LOVE LIFE
	// ==========================================================================================	
	{ text: "The first time I thought I was in love", categories: ["Love Life"] },
	{ text: "A moment that made me believe in love", categories: ["Love Life"] },
	{ text: "A time I completely misread a situation", categories: ["Love Life"] },
	{ text: "The most unexpected connection I’ve had", categories: ["Love Life"] },
	{ text: "A time I took a chance on someone", categories: ["Love Life"] },
	{ text: "A moment that changed how I see relationships", categories: ["Love Life"] },
	{ text: "A time I had to be honest about my feelings", categories: ["Love Life"] },
	{ text: "What I’ve learned about love over time", categories: ["Love Life"] },
	{ text: "A moment I felt truly seen by someone", categories: ["Love Life"] },
	{ text: "A time I didn’t say what I wanted to say", categories: ["Love Life"] },

	{ text: "A moment I realized timing matters", categories: ["Love Life"] },
	{ text: "A time I had to let something go", categories: ["Love Life"] },
	{ text: "A connection that surprised me", categories: ["Love Life"] },
	{ text: "A moment that didn’t go how I imagined", categories: ["Love Life"] },
	{ text: "A time I learned something about myself through someone else", categories: ["Love Life"] },
	{ text: "The difference between expectation and reality in relationships", categories: ["Love Life"] },
	{ text: "A time I followed my heart", categories: ["Love Life"] },
	{ text: "A moment I realized I was overthinking everything", categories: ["Love Life"] },
	{ text: "A time I had to take a risk emotionally", categories: ["Love Life"] },
	{ text: "A moment I felt completely unsure", categories: ["Love Life"] },

	{ text: "A time I learned the importance of communication", categories: ["Love Life"] },
	{ text: "A moment that taught me something about connection", categories: ["Love Life"] },
	{ text: "A time I had to be vulnerable", categories: ["Love Life"] },
	{ text: "A moment I saw things from a different perspective", categories: ["Love Life"] },
	{ text: "A time I realized I needed to grow", categories: ["Love Life"] },
	{ text: "A moment I felt something I didn’t expect", categories: ["Love Life"] },
	{ text: "A time I had to trust my instincts in a relationship", categories: ["Love Life"] },
	{ text: "A moment I realized what I truly wanted", categories: ["Love Life"] },
	{ text: "A time I had to step back and reflect", categories: ["Love Life"] },
	{ text: "A moment that stayed with me", categories: ["Love Life"] },

	{ text: "A time I learned something the hard way about love", categories: ["Love Life"] },
	{ text: "A moment I felt hopeful about the future", categories: ["Love Life"] },
	{ text: "A time I misunderstood someone completely", categories: ["Love Life"] },
	{ text: "A moment I realized how complicated things can be", categories: ["Love Life"] },
	{ text: "A time I had to be patient with myself", categories: ["Love Life"] },
	{ text: "A moment I felt a real connection", categories: ["Love Life"] },
	{ text: "A time I had to be honest with someone else", categories: ["Love Life"] },
	{ text: "A moment I saw things more clearly", categories: ["Love Life"] },
	{ text: "A time I had to choose what was right for me", categories: ["Love Life"] },
	{ text: "A moment I felt unsure but moved forward anyway", categories: ["Love Life"] },

	{ text: "A time I learned to appreciate something I once overlooked", categories: ["Love Life"] },
	{ text: "A moment I realized love looks different than I thought", categories: ["Love Life"] },
	{ text: "A time I had to navigate mixed signals", categories: ["Love Life"] },
	{ text: "A moment I felt completely caught off guard", categories: ["Love Life"] },
	{ text: "A time I learned something about trust", categories: ["Love Life"] },
	{ text: "A moment I had to be brave emotionally", categories: ["Love Life"] },
	{ text: "A time I realized connection takes effort", categories: ["Love Life"] },
	{ text: "A moment I felt closer to someone", categories: ["Love Life"] },
	{ text: "A time I had to rethink what I wanted", categories: ["Love Life"] },
	{ text: "A moment I saw the value of honesty", categories: ["Love Life"] },

	{ text: "A time I realized love isn’t always simple", categories: ["Love Life"] },
	{ text: "A moment I felt something shift", categories: ["Love Life"] },
	{ text: "A time I had to let things unfold naturally", categories: ["Love Life"] },
	{ text: "A moment I felt ready for something new", categories: ["Love Life"] },
	{ text: "A time I learned the importance of timing", categories: ["Love Life"] },
	{ text: "A moment I realized I was growing", categories: ["Love Life"] },
	{ text: "A time I had to listen more than speak", categories: ["Love Life"] },
	{ text: "A moment I felt aligned with what I wanted", categories: ["Love Life"] },
	{ text: "A time I realized I deserved something different", categories: ["Love Life"] },
	{ text: "What love means to me right now", categories: ["Love Life"] },


	// ==========================================================================================
	// PAST, PRESENT & FUTURE
	// ==========================================================================================
	{ text: "A moment from my past that still influences me today", categories: ["Past, Present & Future"] },
	{ text: "What I appreciate more now than I used to", categories: ["Past, Present & Future"] },
	{ text: "How my perspective has changed over time", categories: ["Past, Present & Future"] },
	{ text: "A memory that feels different today", categories: ["Past, Present & Future"] },
	{ text: "What I once believed—and what I believe now", categories: ["Past, Present & Future"] },
	{ text: "A moment that shaped my direction", categories: ["Past, Present & Future"] },
	{ text: "Where I am now compared to where I started", categories: ["Past, Present & Future"] },
	{ text: "A time I didn’t realize the importance of the moment", categories: ["Past, Present & Future"] },
	{ text: "What I would tell a past version of myself", categories: ["Past, Present & Future"] },
	{ text: "How my priorities have changed", categories: ["Past, Present & Future"] },

	{ text: "A moment I wish I could revisit with new understanding", categories: ["Past, Present & Future"] },
	{ text: "What I see differently now", categories: ["Past, Present & Future"] },
	{ text: "A time that felt small but turned out to be important", categories: ["Past, Present & Future"] },
	{ text: "What I’ve carried with me over time", categories: ["Past, Present & Future"] },
	{ text: "How I’ve changed in ways I didn’t expect", categories: ["Past, Present & Future"] },
	{ text: "A moment I didn’t fully understand until later", categories: ["Past, Present & Future"] },
	{ text: "What I’ve learned from looking back", categories: ["Past, Present & Future"] },
	{ text: "A version of myself I’ve outgrown", categories: ["Past, Present & Future"] },
	{ text: "What still feels the same after all this time", categories: ["Past, Present & Future"] },
	{ text: "A time I thought I had everything figured out", categories: ["Past, Present & Future"] },

	{ text: "What the present moment means to me", categories: ["Past, Present & Future"] },
	{ text: "A time I felt completely present", categories: ["Past, Present & Future"] },
	{ text: "What I notice more now than before", categories: ["Past, Present & Future"] },
	{ text: "A moment I slowed down and paid attention", categories: ["Past, Present & Future"] },
	{ text: "What I value most right now", categories: ["Past, Present & Future"] },
	{ text: "A time I became more aware of my surroundings", categories: ["Past, Present & Future"] },
	{ text: "What I’m learning in this stage of life", categories: ["Past, Present & Future"] },
	{ text: "A moment I chose to be present instead of distracted", categories: ["Past, Present & Future"] },
	{ text: "What I’m focused on today", categories: ["Past, Present & Future"] },
	{ text: "A time I realized the importance of now", categories: ["Past, Present & Future"] },

	{ text: "What I imagine for my future", categories: ["Past, Present & Future"] },
	{ text: "A future I once imagined—and how it compares to now", categories: ["Past, Present & Future"] },
	{ text: "What I hope to become", categories: ["Past, Present & Future"] },
	{ text: "A vision I have for what’s ahead", categories: ["Past, Present & Future"] },
	{ text: "What I’m building toward", categories: ["Past, Present & Future"] },
	{ text: "A future version of myself I think about", categories: ["Past, Present & Future"] },
	{ text: "What I want to carry forward into the future", categories: ["Past, Present & Future"] },
	{ text: "A possibility I’m excited about", categories: ["Past, Present & Future"] },
	{ text: "What I’m curious about in the future", categories: ["Past, Present & Future"] },
	{ text: "A direction I didn’t expect to take", categories: ["Past, Present & Future"] },

	{ text: "How my past shaped my present direction", categories: ["Past, Present & Future"] },
	{ text: "A moment where past and present collided", categories: ["Past, Present & Future"] },
	{ text: "What I’ve learned that will shape my future", categories: ["Past, Present & Future"] },
	{ text: "A pattern I’ve noticed over time", categories: ["Past, Present & Future"] },
	{ text: "How I’ve grown in ways I didn’t notice at first", categories: ["Past, Present & Future"] },
	{ text: "What I’ve let go of—and what I’ve kept", categories: ["Past, Present & Future"] },
	{ text: "A time I realized I was repeating something from the past", categories: ["Past, Present & Future"] },
	{ text: "What I’ve carried forward from earlier in life", categories: ["Past, Present & Future"] },
	{ text: "A moment I saw my past differently because of the present", categories: ["Past, Present & Future"] },
	{ text: "What I’m becoming that my past self wouldn’t expect", categories: ["Past, Present & Future"] },

	{ text: "A moment I felt connected to my past and future at the same time", categories: ["Past, Present & Future"] },
	{ text: "What I’ve learned about time through my experiences", categories: ["Past, Present & Future"] },
	{ text: "A moment that made me think about where I’m headed", categories: ["Past, Present & Future"] },
	{ text: "How my understanding of life has evolved", categories: ["Past, Present & Future"] },
	{ text: "A time I paused to reflect on everything so far", categories: ["Past, Present & Future"] },
	{ text: "What I want to remember moving forward", categories: ["Past, Present & Future"] },
	{ text: "A moment I realized I was on a different path", categories: ["Past, Present & Future"] },
	{ text: "How I define progress in my life", categories: ["Past, Present & Future"] },
	{ text: "What I’ve learned about change over time", categories: ["Past, Present & Future"] },
	{ text: "What this chapter of my life means to me", categories: ["Past, Present & Future"] },	
	
	
	

	// ==========================================================================================
	// TALL TALES
	// ==========================================================================================
	{ text: "The day I accidentally became a local legend", categories: ["Tall Tales"] },
	{ text: "How I survived the most unbelievable situation", categories: ["Tall Tales"] },
	{ text: "The time I discovered I had an unusual ability", categories: ["Tall Tales"] },
	{ text: "The most extraordinary day of my life", categories: ["Tall Tales"] },
	{ text: "How I got into a situation no one believed", categories: ["Tall Tales"] },
	{ text: "The day everything went completely out of control", categories: ["Tall Tales"] },
	{ text: "How I became known for something ridiculous", categories: ["Tall Tales"] },
	{ text: "The strangest thing that ever happened to me", categories: ["Tall Tales"] },
	{ text: "The time I outsmarted an impossible situation", categories: ["Tall Tales"] },
	{ text: "How one small decision changed everything in the wildest way", categories: ["Tall Tales"] },

	{ text: "The day I had to think faster than ever before", categories: ["Tall Tales"] },
	{ text: "How I got myself into the most unbelievable mess", categories: ["Tall Tales"] },
	{ text: "The time I broke all expectations", categories: ["Tall Tales"] },
	{ text: "The day nothing followed the rules anymore", categories: ["Tall Tales"] },
	{ text: "How I handled a situation no one was prepared for", categories: ["Tall Tales"] },
	{ text: "The moment everything escalated beyond control", categories: ["Tall Tales"] },
	{ text: "The time I discovered something no one else could explain", categories: ["Tall Tales"] },
	{ text: "How I ended up in the most unlikely place", categories: ["Tall Tales"] },
	{ text: "The day reality didn’t make sense anymore", categories: ["Tall Tales"] },
	{ text: "The time I had to rely on pure instinct", categories: ["Tall Tales"] },

	{ text: "The most exaggerated version of a normal day", categories: ["Tall Tales"] },
	{ text: "How I accidentally caused something much bigger than expected", categories: ["Tall Tales"] },
	{ text: "The time I was in the wrong place at the perfect time", categories: ["Tall Tales"] },
	{ text: "The day I had to deal with something completely unexpected", categories: ["Tall Tales"] },
	{ text: "How I became part of a story no one could explain", categories: ["Tall Tales"] },
	{ text: "The time I faced something I couldn’t believe", categories: ["Tall Tales"] },
	{ text: "The day I pushed things just a little too far", categories: ["Tall Tales"] },
	{ text: "How I handled the most ridiculous challenge ever", categories: ["Tall Tales"] },
	{ text: "The time everything worked out in the strangest way", categories: ["Tall Tales"] },
	{ text: "The day I realized I was in over my head", categories: ["Tall Tales"] },

	{ text: "How I ended up in the most unexpected situation imaginable", categories: ["Tall Tales"] },
	{ text: "The time I had to improvise my way out of chaos", categories: ["Tall Tales"] },
	{ text: "The day something completely unbelievable happened", categories: ["Tall Tales"] },
	{ text: "How I turned a small problem into something massive", categories: ["Tall Tales"] },
	{ text: "The time I couldn’t explain what was happening", categories: ["Tall Tales"] },
	{ text: "The day I discovered something no one warned me about", categories: ["Tall Tales"] },
	{ text: "How I survived a situation that made no sense", categories: ["Tall Tales"] },
	{ text: "The time I had to keep going no matter how strange things got", categories: ["Tall Tales"] },
	{ text: "The day I learned something in the most unusual way", categories: ["Tall Tales"] },
	{ text: "How I got out of a situation that kept getting worse", categories: ["Tall Tales"] },

	{ text: "The time I experienced something truly unbelievable", categories: ["Tall Tales"] },
	{ text: "The day I realized normal rules didn’t apply", categories: ["Tall Tales"] },
	{ text: "How I managed to stay one step ahead of chaos", categories: ["Tall Tales"] },
	{ text: "The time I had to make sense of the impossible", categories: ["Tall Tales"] },
	{ text: "The day everything became more than I expected", categories: ["Tall Tales"] },
	{ text: "How I dealt with something completely out of the ordinary", categories: ["Tall Tales"] },
	{ text: "The time I had to keep a straight face through something absurd", categories: ["Tall Tales"] },
	{ text: "The day I became part of something unbelievable", categories: ["Tall Tales"] },
	{ text: "How I turned confusion into something even bigger", categories: ["Tall Tales"] },
	{ text: "The time I realized I couldn’t turn back", categories: ["Tall Tales"] },

	{ text: "The day everything started small and ended enormous", categories: ["Tall Tales"] },
	{ text: "How I found myself in a situation no one could predict", categories: ["Tall Tales"] },
	{ text: "The time I had to trust something that made no sense", categories: ["Tall Tales"] },
	{ text: "The day I handled something no one else could", categories: ["Tall Tales"] },
	{ text: "How I turned a ridiculous moment into something legendary", categories: ["Tall Tales"] },
	{ text: "The time I became known for something unbelievable", categories: ["Tall Tales"] },
	{ text: "The day I had to keep up with something impossible", categories: ["Tall Tales"] },
	{ text: "How I ended up telling a story no one believed", categories: ["Tall Tales"] },
	{ text: "The time everything unfolded in the strangest possible way", categories: ["Tall Tales"] },
	{ text: "The day I realized I had gone too far to stop", categories: ["Tall Tales"] },


	// ==========================================================================================
  // TM ROGERS PARK THEMES
	// ==========================================================================================
  { text: "Feel the Rush", categories: ["RPTM Themes"] },
	{ text: "Unleash Your Inner Hero", categories: ["RPTM Themes"] },
	
	
	// ==========================================================================================
  // TURNING POINTS
	// ==========================================================================================
	{ text: "A decision that changed everything", categories: ["Turning Points"] },
	{ text: "A moment I almost chose differently", categories: ["Turning Points"] },
	{ text: "A time my path shifted unexpectedly", categories: ["Turning Points"] },
	{ text: "A moment that redirected my life", categories: ["Turning Points"] },
	{ text: "A choice I didn’t realize was so important", categories: ["Turning Points"] },
	{ text: "A time I took a risk that paid off", categories: ["Turning Points"] },
	{ text: "A moment I knew things would be different from then on", categories: ["Turning Points"] },
	{ text: "A time I had to make a difficult decision", categories: ["Turning Points"] },
	{ text: "A moment that forced me to grow", categories: ["Turning Points"] },
	{ text: "A time I stepped into something new", categories: ["Turning Points"] },

	{ text: "A moment I had to choose between two paths", categories: ["Turning Points"] },
	{ text: "A time everything changed faster than I expected", categories: ["Turning Points"] },
	{ text: "A moment I realized I couldn’t go back", categories: ["Turning Points"] },
	{ text: "A decision that led me somewhere unexpected", categories: ["Turning Points"] },
	{ text: "A time I trusted myself and it mattered", categories: ["Turning Points"] },
	{ text: "A moment I saw a new possibility", categories: ["Turning Points"] },
	{ text: "A time I had to let go to move forward", categories: ["Turning Points"] },
	{ text: "A moment I realized I was on the wrong path", categories: ["Turning Points"] },
	{ text: "A time I chose growth over comfort", categories: ["Turning Points"] },
	{ text: "A moment that redefined what I wanted", categories: ["Turning Points"] },

	{ text: "A time I made a bold move", categories: ["Turning Points"] },
	{ text: "A moment I had to trust the unknown", categories: ["Turning Points"] },
	{ text: "A time I changed direction completely", categories: ["Turning Points"] },
	{ text: "A moment that challenged everything I believed", categories: ["Turning Points"] },
	{ text: "A time I had to take control of my situation", categories: ["Turning Points"] },
	{ text: "A moment I realized something had to change", categories: ["Turning Points"] },
	{ text: "A time I followed a different path than expected", categories: ["Turning Points"] },
	{ text: "A moment I chose to begin again", categories: ["Turning Points"] },
	{ text: "A time I faced a crossroads", categories: ["Turning Points"] },
	{ text: "A moment that changed how I saw myself", categories: ["Turning Points"] },

	{ text: "A time I had to act without certainty", categories: ["Turning Points"] },
	{ text: "A moment I made a decision under pressure", categories: ["Turning Points"] },
	{ text: "A time I realized I had more control than I thought", categories: ["Turning Points"] },
	{ text: "A moment I chose differently than I normally would", categories: ["Turning Points"] },
	{ text: "A time I had to step up in a big way", categories: ["Turning Points"] },
	{ text: "A moment I took responsibility for my direction", categories: ["Turning Points"] },
	{ text: "A time I recognized an opportunity and took it", categories: ["Turning Points"] },
	{ text: "A moment that changed my priorities", categories: ["Turning Points"] },
	{ text: "A time I had to commit fully to something", categories: ["Turning Points"] },
	{ text: "A moment I moved forward despite doubt", categories: ["Turning Points"] },

	{ text: "A time I realized something wasn’t working anymore", categories: ["Turning Points"] },
	{ text: "A moment I had to pivot quickly", categories: ["Turning Points"] },
	{ text: "A time I took a step that felt uncertain", categories: ["Turning Points"] },
	{ text: "A moment I embraced a new direction", categories: ["Turning Points"] },
	{ text: "A time I changed my mindset and everything followed", categories: ["Turning Points"] },
	{ text: "A moment I saw the bigger picture clearly", categories: ["Turning Points"] },
	{ text: "A time I chose to move on", categories: ["Turning Points"] },
	{ text: "A moment that helped define who I am", categories: ["Turning Points"] },
	{ text: "A time I realized I was ready for something new", categories: ["Turning Points"] },
	{ text: "A moment I stopped holding myself back", categories: ["Turning Points"] },

	{ text: "A time I made a decision I was afraid of", categories: ["Turning Points"] },
	{ text: "A moment I chose to trust the process", categories: ["Turning Points"] },
	{ text: "A time I saw an ending as a beginning", categories: ["Turning Points"] },
	{ text: "A moment I realized I had changed", categories: ["Turning Points"] },
	{ text: "A time I made a choice that shaped my future", categories: ["Turning Points"] },
	{ text: "A moment I stepped into a new version of myself", categories: ["Turning Points"] },
	{ text: "A time I stopped waiting and took action", categories: ["Turning Points"] },
	{ text: "A moment I realized the direction I wanted to go", categories: ["Turning Points"] },
	{ text: "A time I chose differently than before", categories: ["Turning Points"] },
	{ text: "A moment that marked a new chapter in my life", categories: ["Turning Points"] },	



	// ==========================================================================================	
	// WHAT IF...?
	// ==========================================================================================
	{ text: "What if I had made a different choice?", categories: ["What If…?"] },
	{ text: "What if failure didn’t matter?", categories: ["What If…?"] },
	{ text: "What if I could go back and change one moment?", categories: ["What If…?"] },
	{ text: "What if everything worked out exactly as planned?", categories: ["What If…?"] },
	{ text: "What if I trusted myself sooner?", categories: ["What If…?"] },
	{ text: "What if I had taken that opportunity?", categories: ["What If…?"] },
	{ text: "What if I had said yes instead of no?", categories: ["What If…?"] },
	{ text: "What if I had said no instead of yes?", categories: ["What If…?"] },
	{ text: "What if I never tried?", categories: ["What If…?"] },
	{ text: "What if I started earlier?", categories: ["What If…?"] },

	{ text: "What if I stopped overthinking everything?", categories: ["What If…?"] },
	{ text: "What if I did the opposite of what I usually do?", categories: ["What If…?"] },
	{ text: "What if I followed my instincts every time?", categories: ["What If…?"] },
	{ text: "What if I wasn’t afraid to fail?", categories: ["What If…?"] },
	{ text: "What if I let go of control?", categories: ["What If…?"] },
	{ text: "What if I focused on what really matters?", categories: ["What If…?"] },
	{ text: "What if I gave myself more time?", categories: ["What If…?"] },
	{ text: "What if I trusted the process?", categories: ["What If…?"] },
	{ text: "What if I believed in myself fully?", categories: ["What If…?"] },
	{ text: "What if I didn’t compare myself to others?", categories: ["What If…?"] },

	{ text: "What if everything I needed was already here?", categories: ["What If…?"] },
	{ text: "What if I changed my perspective?", categories: ["What If…?"] },
	{ text: "What if I saw things differently?", categories: ["What If…?"] },
	{ text: "What if I challenged my own beliefs?", categories: ["What If…?"] },
	{ text: "What if I questioned what I’ve always accepted?", categories: ["What If…?"] },
	{ text: "What if I redefined success for myself?", categories: ["What If…?"] },
	{ text: "What if I stopped waiting for the right moment?", categories: ["What If…?"] },
	{ text: "What if I embraced uncertainty?", categories: ["What If…?"] },
	{ text: "What if I focused on progress instead of perfection?", categories: ["What If…?"] },
	{ text: "What if I trusted where I am right now?", categories: ["What If…?"] },

	{ text: "What if I chose a completely different path?", categories: ["What If…?"] },
	{ text: "What if I started something new today?", categories: ["What If…?"] },
	{ text: "What if I followed through this time?", categories: ["What If…?"] },
	{ text: "What if I gave it one more try?", categories: ["What If…?"] },
	{ text: "What if I stopped holding myself back?", categories: ["What If…?"] },
	{ text: "What if I made a bold decision?", categories: ["What If…?"] },
	{ text: "What if I took a chance on something unexpected?", categories: ["What If…?"] },
	{ text: "What if I trusted the unknown?", categories: ["What If…?"] },
	{ text: "What if I stepped outside my comfort zone?", categories: ["What If…?"] },
	{ text: "What if I did something I’ve never done before?", categories: ["What If…?"] },

	{ text: "What if I looked at my past differently?", categories: ["What If…?"] },
	{ text: "What if I appreciated where I am more?", categories: ["What If…?"] },
	{ text: "What if I focused on the present moment?", categories: ["What If…?"] },
	{ text: "What if I let go of what I can’t control?", categories: ["What If…?"] },
	{ text: "What if I gave myself more credit?", categories: ["What If…?"] },
	{ text: "What if I saw my challenges as opportunities?", categories: ["What If…?"] },
	{ text: "What if I changed how I respond to things?", categories: ["What If…?"] },
	{ text: "What if I embraced who I am becoming?", categories: ["What If…?"] },
	{ text: "What if I trusted that things will work out?", categories: ["What If…?"] },
	{ text: "What if I focused on what I can control?", categories: ["What If…?"] },

	{ text: "What if I imagined a different future?", categories: ["What If…?"] },
	{ text: "What if I allowed myself to dream bigger?", categories: ["What If…?"] },
	{ text: "What if I created my own definition of success?", categories: ["What If…?"] },
	{ text: "What if I stopped limiting myself?", categories: ["What If…?"] },
	{ text: "What if I believed something better was possible?", categories: ["What If…?"] },
	{ text: "What if I followed what excites me?", categories: ["What If…?"] },
	{ text: "What if I explored a different version of my life?", categories: ["What If…?"] },
	{ text: "What if I trusted my future self?", categories: ["What If…?"] },
	{ text: "What if I leaned into curiosity instead of fear?", categories: ["What If…?"] },
	{ text: "What if I chose possibility over doubt?", categories: ["What If…?"] },


	// ==========================================================================================	
	// WORK LIFE
	// ==========================================================================================
	{ text: "My first real job experience", categories: ["Work Life"] },
	{ text: "A moment I felt proud at work", categories: ["Work Life"] },
	{ text: "A lesson I learned on the job", categories: ["Work Life"] },
	{ text: "A time I had to figure something out quickly at work", categories: ["Work Life"] },
	{ text: "What work has taught me about people", categories: ["Work Life"] },
	{ text: "A challenging day at work", categories: ["Work Life"] },
	{ text: "A time I made a mistake at work", categories: ["Work Life"] },
	{ text: "A moment I stepped up at work", categories: ["Work Life"] },
	{ text: "A time I had to learn something new quickly", categories: ["Work Life"] },
	{ text: "The most unexpected part of my job", categories: ["Work Life"] },

	{ text: "A time I had to deal with pressure at work", categories: ["Work Life"] },
	{ text: "A moment I realized I had grown professionally", categories: ["Work Life"] },
	{ text: "A time I had to work with a difficult situation", categories: ["Work Life"] },
	{ text: "What I’ve learned about teamwork", categories: ["Work Life"] },
	{ text: "A moment I felt out of my depth at work", categories: ["Work Life"] },
	{ text: "A time I had to adapt to change at work", categories: ["Work Life"] },
	{ text: "A lesson I learned from a colleague", categories: ["Work Life"] },
	{ text: "A moment I had to take initiative", categories: ["Work Life"] },
	{ text: "A time I had to manage my time effectively", categories: ["Work Life"] },
	{ text: "A situation that tested my patience at work", categories: ["Work Life"] },

	{ text: "A time I had to communicate clearly under pressure", categories: ["Work Life"] },
	{ text: "A moment I realized the importance of responsibility", categories: ["Work Life"] },
	{ text: "A time I had to solve a problem on the spot", categories: ["Work Life"] },
	{ text: "A moment I learned the value of preparation", categories: ["Work Life"] },
	{ text: "A time I had to handle feedback", categories: ["Work Life"] },
	{ text: "A moment I had to stay calm in a stressful situation", categories: ["Work Life"] },
	{ text: "A time I had to learn from failure at work", categories: ["Work Life"] },
	{ text: "A moment I realized the importance of communication", categories: ["Work Life"] },
	{ text: "A time I had to balance multiple responsibilities", categories: ["Work Life"] },
	{ text: "A moment I saw the bigger picture at work", categories: ["Work Life"] },

	{ text: "A time I had to adjust my expectations at work", categories: ["Work Life"] },
	{ text: "A moment I had to trust my abilities", categories: ["Work Life"] },
	{ text: "A time I had to work outside my comfort zone", categories: ["Work Life"] },
	{ text: "A moment I realized the value of consistency", categories: ["Work Life"] },
	{ text: "A time I had to make a decision quickly", categories: ["Work Life"] },
	{ text: "A moment I learned the importance of listening", categories: ["Work Life"] },
	{ text: "A time I had to collaborate with others", categories: ["Work Life"] },
	{ text: "A moment I had to stay focused despite distractions", categories: ["Work Life"] },
	{ text: "A time I had to take ownership of something", categories: ["Work Life"] },
	{ text: "A moment I realized the importance of accountability", categories: ["Work Life"] },

	{ text: "A time I had to rethink my approach at work", categories: ["Work Life"] },
	{ text: "A moment I had to step into a leadership role", categories: ["Work Life"] },
	{ text: "A time I had to deal with uncertainty at work", categories: ["Work Life"] },
	{ text: "A moment I realized the value of persistence at work", categories: ["Work Life"] },
	{ text: "A time I had to manage expectations", categories: ["Work Life"] },
	{ text: "A moment I had to stay motivated", categories: ["Work Life"] },
	{ text: "A time I had to learn from someone else’s perspective", categories: ["Work Life"] },
	{ text: "A moment I realized the importance of adaptability", categories: ["Work Life"] },
	{ text: "A time I had to stay organized under pressure", categories: ["Work Life"] },
	{ text: "A moment I had to overcome self-doubt at work", categories: ["Work Life"] },

	{ text: "A time I had to improve a skill for my job", categories: ["Work Life"] },
	{ text: "A moment I realized how far I’ve come professionally", categories: ["Work Life"] },
	{ text: "A time I had to deal with an unexpected challenge at work", categories: ["Work Life"] },
	{ text: "A moment I had to trust the process at work", categories: ["Work Life"] },
	{ text: "A time I had to support someone else at work", categories: ["Work Life"] },
	{ text: "A moment I realized the importance of growth", categories: ["Work Life"] },
	{ text: "A time I had to maintain focus over time", categories: ["Work Life"] },
	{ text: "A moment I had to push through a difficult task", categories: ["Work Life"] },
	{ text: "A time I had to learn from experience", categories: ["Work Life"] },
	{ text: "What work has taught me about myself", categories: ["Work Life"] },
	
];